RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/1 [00:00<?, ?it/s]
  0%|          | 0/112 [00:00<?, ?it/s][A
  1%|          | 1/112 [21:19<39:26:55, 1279.42s/it][A
  2%|▏         | 2/112 [21:27<16:14:45, 531.69s/it] [A
  4%|▎         | 4/112 [22:17<6:25:15, 214.03s/it] [A
  7%|▋         | 8/112 [22:25<2:14:58, 77.87s/it] [A
 20%|█▉        | 22/112 [22:25<27:45, 18.51s/it] [A
 24%|██▍       | 27/112 [22:25<18:54, 13.35s/it][A
 53%|█████▎    | 59/112 [22:30<03:24,  3.85s/it][A
 53%|█████▎    | 59/112 [22:47<03:24,  3.85s/it][A
 65%|██████▌   | 73/112 [25:13<04:04,  6.27s/it][A
 66%|██████▌   | 74/112 [26:41<05:34,  8.79s/it][A
 69%|██████▉   | 77/112 [28:59<07:38, 13.11s/it][A
 70%|██████▉   | 78/112 [29:18<07:36, 13.42s/it][A
 72%|███████▏  | 81/112 [30:08<07:14, 14.00s/it][A
 75%|███████▌  | 84/112 [30:49<06:29, 13.92s/it][A
 78%|███████▊  | 87/112 [31:16<05:19, 12.78s/it][A
 81%|████████▏ | 91/112 [31:21<03:15,  9.32s/it][A
 81%|████████▏ | 91/112 [31:37<03:15,  9.32s/it][A
 84%|████████▍ | 94/112 [31:39<02:32,  8.48s/it][A
 90%|█████████ | 101/112 [31:39<00:51,  4.69s/it][A100%|██████████| 112/112 [31:39<00:00, 16.96s/it]
100%|██████████| 1/1 [31:45<00:00, 1905.00s/it]100%|██████████| 1/1 [31:45<00:00, 1905.01s/it]
Exception ignored in: <function Pool.__del__ at 0x2ab24eea54c0>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
