RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/100 [00:00<?, ?it/s]  1%|          | 1/100 [00:48<1:20:00, 48.48s/it]  7%|▋         | 7/100 [00:50<08:16,  5.34s/it]    8%|▊         | 8/100 [00:51<07:08,  4.66s/it] 29%|██▉       | 29/100 [00:52<00:53,  1.33it/s] 29%|██▉       | 29/100 [01:10<00:53,  1.33it/s] 73%|███████▎  | 73/100 [01:13<00:15,  1.77it/s] 74%|███████▍  | 74/100 [01:14<00:15,  1.73it/s] 81%|████████  | 81/100 [01:14<00:09,  2.09it/s] 84%|████████▍ | 84/100 [01:15<00:07,  2.27it/s]100%|██████████| 100/100 [01:15<00:00,  1.33it/s]
Exception ignored in: <function Pool.__del__ at 0x2b799505b160>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
